name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: mayank2295
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: "Generated Snake Animation"
          add: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
